// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ProjectTimeTracker
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidProjectTimeTrackerPackageString = "12345678-abcd-4321-abcd-1234567890ab";
        public static Guid guidProjectTimeTrackerPackage = new Guid(guidProjectTimeTrackerPackageString);

        public const string guidProjectTimeTrackerPackageCmdSetString = "722e2d72-0764-418c-9209-8841b2d0b276";
        public static Guid guidProjectTimeTrackerPackageCmdSet = new Guid(guidProjectTimeTrackerPackageCmdSetString);

        public const string guidImagesString = "a8089f72-5af5-49bc-8b5e-e7760f3b62ae";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int TimeTrackerWindowCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}